apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: serve-model-task
spec:
  params:
    - name: image
      type: string
      description: "The container image to use for serving"
    - name: prompt
      type: string
      description: "The prompt to pass to serve.py"
  workspaces:
    - name: source
  steps:
    - name: serve
      image: "$(params.image)"
      script: |
        #!/usr/bin/env bash
        set -e
        cd /workspace/source/training_process
        python3 serve.py "$(params.prompt)"

