apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: ""    # or "standard" if your PVC uses that
  hostPath:
    path: /mnt/training_process
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: source-pv

